services:
  - type: web
    name: disease-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dp_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: dp_project.settings
