services:
  - type: web
    name: disease-prediction
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn dp_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: dp_project.settings
      - key: PYTHON_VERSION
        value: 3.10
